"""Initial schema

Revision ID: 76c2febda894
Revises: 
Create Date: 2026-04-07 18:21:27.878782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76c2febda894'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_style_guides',
    sa.Column('age_group', sa.String(), nullable=False),
    sa.Column('sentence_rules', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('emotional_expression', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('page_guidelines', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.PrimaryKeyConstraint('age_group')
    )
    op.create_table('emotional_arc_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('target_ages', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('stages', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_rails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prohibitions', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('required_elements', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('child_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('comfort_object', sa.String(), nullable=True),
    sa.Column('friend_name', sa.String(), nullable=True),
    sa.Column('favorite_animal', sa.String(), nullable=True),
    sa.Column('character_sheet_url', sa.String(), nullable=True),
    sa.Column('photo_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('intent_analysis', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('scene_plan', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('illustration_prompt', sa.String(), nullable=False),
    sa.Column('illustration_url', sa.String(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_pages')
    op.drop_table('stories')
    op.drop_table('child_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('safety_rails')
    op.drop_table('emotional_arc_templates')
    op.drop_table('age_style_guides')
    # ### end Alembic commands ###
